services:
  mysql:
    image: docker.arvancloud.ir/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shariff_db
      MYSQL_USER: psg
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    # networks:
    #   - shariff-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p password"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always