CREATE TABLE IF NOT EXISTS answer (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    form_response_id BIGINT REFERENCES form_response(id) ON DELETE CASCADE,
    question_id BIGINT REFERENCES question(id) ON DELETE CASCADE,
    answer_text TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
